### PR TITLE
bunch of stuff

### PR DESCRIPTION
**Pull request by Kruddle**
Added content to about page with lorem ipsum filler text. Added email page with no backend setup. Added background color for pages. Added general mobile compatibility.

### CODE REVIEW

**Comment by juicylime** [comment]
@Kruddle Could you add the .idea folder in the .gitignore file. I think thats specific to your IDE.

**Comment by juicylime** [comment]
@Kruddle I'm not sure if we would be able to send any emails. It's hosting on github pages and it only serves static front end stuff. AFIAK it doesn't have the ability to execute any backend code. I would just reference the company email on that page probably.

Edit: Yeah so it's not possible to send emails with github pages unless we want to setup other services which would probably cost money. We could just leave the info email in the contact form box for now and if we ever switch from github pages to something else we could put the contact form back in.

**Comment by juicylime** [comment]
@Kruddle Could you make it so that the header logo and the nav bar on the home screen is the same size as the other screens?

**Comment by juicylime** [comment]
@Kruddle I really like what you did with the banner text by adding a white stroke to it to make it more easy to read. I see that you only added it to the text that was hard to read but maybe it might be better to just add it to the entire text? Thoughts?

**Comment by juicylime** [comment]
@Kruddle Overall, the site looks way better thanks

**Comment by Kruddle** [comment]
@juicylime You're welcome it was relaxing to work on. I'll make those changes when I'm over this cold. And I'll see how the smaller text looks if I add the white.

**Comment by Kruddle** [comment]
> @Kruddle Could you make it so that the header logo and the nav bar on the home screen is the same size as the other screens?
 @juicylime I am unable to replicate this issue. On my end they are all identical. I may have fixed the issue.

**Comment by Kruddle** [comment]
@juicylime Adding a white stoke to text ends up looking choppy and pixelated the smaller the font size. I suggest using it on banners only.

**Comment by Kruddle** [comment]
@juicylime 
- Switched the contact page to show the email only. 
- Possibly fixed the nav sizing on the home page.
- Added .idea to .gitignore

**Comment by Kruddle** [comment]
@juicylime
Some parts look funky on a 360x wide viewport. Need to make some adjustments to mobile view.

**Pull request merged**
